version: '3.7'
services:
  api:
    restart: on-failure
    build:
      context: application
    env_file:
      - .env
    networks:
      - aplicacao    
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx-docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - aplicacao  
    depends_on:
      - api    
 
networks:
  aplicacao:
